- include: system_environment.yml
  tags: sysenv

- include: setup_postgres.yml
  tags: database

- include: setup_rabbitmq.yml
  tags: broker

- include: setup_certbot.yml
  tags: certbot

- include: setup_webapp.yml
  tags: webapp

- include: setup_webui.yml
  tags:
    - webapp
    - webui
