---
- name: Checkout cloudlaunch client source
  git:
    repo: https://github.com/galaxyproject/cloudlaunch-ui
    dest: "{{ ui_install_dir }}"
    accept_hostkey: yes
    force: yes
    version: master
  register: gitout

- name: Git update output  # Enable with -v flag to ansible-playbook
  debug:
    var: gitout
    verbosity: 1

- name: Install client requirements
  npm:
    path: "{{ ui_install_dir }}"
    state: latest
  tags:
    - install
    - deploy

- name: Adjust backend API url
  replace:
    dest: "{{ ui_install_dir }}/src/app/app.settings.ts"
    regexp: "return ''"
    replace: "return '/cloudlaunch'"
  tags:
    - install
    - deploy

- name: Build UI using angular-cli
  shell: npm run build
  args:
    chdir: "{{ ui_install_dir }}"
  tags:
    - install
    - deploy

- name: Change ownership of cloudlaunch client to web user
  file:
    recurse: yes
    path: "{{ ui_install_dir }}/dist"
    state: directory
    owner: cloudlaunch
    group: www-data
    mode: 0755
  notify:
   - reload nginx
   - reload supervisor
   - restart supervisor
...
